config/routes.rb
Rails.application.routes.draw do
  resources :subjects do
    resources :steps
  end

  root 'welcome#index'

end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :subject
  validates :title, presence: true
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :steps
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_subject, except: :destroy
  before_action :set_step, only: [:edit, :update, :destroy]

  # GET /steps
  def index
    @steps = @subject.steps
  end

  # GET /steps/1
  # def show
  # end

  # GET /steps/new
  def new
    @step = @subject.steps.build
  end

  # GET /steps/1/edit
  def edit
  end

  # POST /steps
  def create
    @step = @subject.steps.build(step_params)

    if @step.save
      flash[:notice] = 'Step was successfully created.'
      redirect_to subject_url(@subject)
    else
      flash[:error] = 'Step could not be saved.'
      render :new
    end
  end

  # PATCH/PUT /steps/1
  def update
    if @step.update(step_params)
      flash[:notice] = 'Step was successfully updated.'
      redirect_to subject_steps_url(@subject)
    else
      flash[:error] = 'Step could not be saved.'
      render :edit
    end
  end

  # DELETE /steps/1
  def destroy
    @step.destroy
    flash[:notice] = 'Step was successfully destroyed.'
    redirect_to subject_steps_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_step
    @step = Step.find(params[:id])
  end

  def set_subject
    @subject = Subject.find(params[:subject_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def step_params
    params.require(:step).permit(:title, :detail)
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  def show
    @steps = Step.where(subject_id: @subject)
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      flash[:notice] = 'Subject was successfully created.'
      redirect_to @subject
    else
      flash[:error] = 'Subject could not be saved.'
      render :new
    end
  end

  # PATCH/PUT /subjects/1
  def update
    if @subject.update(subject_params)
      flash[:notice] = 'Subject was successfully updated.'
      redirect_to @subject
    else
      flash[:error] = 'Subject could not be saved.'
      render :edit
    end
  end

  # DELETE /subjects/1
  def destroy
    @subject.destroy
    flash[:notice] = 'Subject was successfully destroyed.'
    redirect_to subjects_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subject
    @subject = Subject.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def subject_params
    params.require(:subject).permit(:name, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HowTo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/steps/_form.html.erb
<%= form_for [@subject, @step] do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_area :detail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing Step for <%= @subject.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', subject_steps_path(@subject) %>

app/views/steps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Steps for <%= @subject.name %></h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><strong><%= step.title %></strong></td>
        <td><%= step.detail %></td>
        <td><%= link_to 'Edit', edit_subject_step_path(@subject, step) %></td>
        <td><%= link_to 'Destroy', [@subject, step], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Step', new_subject_step_path %> |
<%= link_to 'Back', @subject %>

app/views/steps/new.html.erb
<h1>New Step for <%= @subject.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', @subject %>

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><strong><%= subject.name %></strong></td>
        <td><%= subject.description %></td>
        <td><%= link_to 'Show', subject_path(subject) %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @subject.description %>
</p>

<p>Follow these steps for <%= @subject.name %>:</p>
<ol>
  <% @steps.each do |step| %>
    <li><strong><%= step.title %></strong> <%= step.detail %></li>
  <% end %>
</ol>

<%= link_to 'Add Step', new_subject_step_path(@subject) %> |
<%= link_to 'Edit Steps', subject_steps_path(@subject) %><br>
<%= link_to 'Edit Subject', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<p>This is my collection of
<%= link_to 'How To Subjects', subjects_path %>.<p>